ARG version
FROM almalinux:${version:-9}
ARG surname=nallam
ARG firstname=srikanth
ARG duration=120hrs
ENV duration=${duration}
RUN echo "surname:${surname} and firstname:${firstname}} and duration:${duration}"
CMD [ "sleep" , "100" ]