FROM almalinux:9
ADD https://www.google.com/search?q=hulk&oq=hulk&gs_lcrp=EgZjaHJvbWUqBwgAEAAYjwIyBwgAEAAYjwIyCggBEC4YsQMYgAQyCggCEC4YsQMYgAQyCggDEC4YsQMYgAQyCggEEAAYsQMYgAQyBwgFEAAYgAQyBwgGEC4YgAQyBwgHEAAYgAQyCggIEC4YsQMYgAQyBwgJEC4YgATSAQgxMTExajBqN6gCALACAA&sourceid=chrome&source=chrome.ob&ie=UTF-8  /app/
CMD ["sleep" , "100"]